### ISSUE TITLE
Test for slow consumer

### ISSUE THREAD

**Issue by nichoth** [nichoth/pull-combine-latest#2]
I think we would need to check that the same `emit` function (from the sink that consumes `combine`) is not called more than once. Make a "queue" each time drain is called, then read from the queue instead of the streams when our source is called. If the queue is empty, then call drain again.

**Comment by nichoth** [comment]
@ahdinosaur I don't think it is possible to do this algorithm if your source streams are a combination of sync and async. The purpose of using sync code in streams is for performance? If we read our sync sources as quickly as possible, then the stack will never clear and we will never get to the async sources until after the sync sources have ended. Maybe I'm wrong, but that seems right.

I guess the solution is to buffer the entire synchronous stream, then emit their values as the async ones resolve, like pull-pushable. This makes sense b/c a synchronous stream is by definition finite or already buffered. Ok, nevermind, this is what I need to do. This means that only the last value from a sync stream would ever be emitted if there is also an async stream in the sources. That's fine. We could also emit null values if a stream hasn't returned yet. The combined stream could then be filtered to produce the same end result. Maybe that's better. Then I could compose a stream that does the original idea. Probably easier to build also.

**Comment by ahdinosaur** [comment]
in the [other issue i mentioned](https://github.com/nichoth/pull-combine-latest/issues/3#issuecomment-246227425), an approach where you read each individual stream once per read of the combined stream.

but from what you're saying now, i get what you mean about a much different approach, where each stream is drained independently for any values as they return. emitting null values for streams that haven't returned sounds good to me. :+1:

**Comment by nichoth** [comment]
Fixed. Good lord I never want to write synchronous code again. Yall are crazy.

**Comment by ahdinosaur** [comment]
haha yep, congrats @nichoth! :smile_cat:
